pracproject/myproject/myapp/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home_page'),
    url(r'^about/$', views.PersonListView.as_view(), name='person_list'),
    url(r'^person_detail/(?P<pk>\d+)/$', views.PersonDetailView.as_view(), name='person_detail'),
    url(r'^add/$', views.CreatePersonView.as_view(), name='add_person'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeletePersonView.as_view(), name='delete_person'),
    url(r'^update/(?P<pk>\d+)/$', views.UpdatePersonView.as_view(), name='update_person'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^user_login/$', auth_views.LoginView.as_view(template_name='myapp/user_login.html'), name='user_login'),
    url(r'^new_customer_entry/$', views.CustomerEntryView.as_view(), name='new_customer_entry'),
    url(r'^customer_list/$', views.CustomerListView.as_view(), name='customer_list'),
    url(r'^update_customer/(?P<pk>\d+)/$', views.UpdateCustomerView.as_view(), name='update_customer'),
    url(r'^customer_information/(?P<pk>\d+)/$', views.CustomerInformation.as_view(), name='customer_info'),
    url(r'^practice/$', views.Practice.as_view(), name='practice')

]

pracproject/myproject/myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('myapp.urls')),
    url(r'^accounts/login/$', views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', views.LogoutView.as_view(), name='logout'),

]

pracproject/myproject/myapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User, PermissionsMixin


# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField()

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse("person_list")


class NewUser(User, PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)


class CustomerEntry(models.Model):
    rst_number = models.AutoField(primary_key=True)
    customer_name = models.CharField(max_length=200)
    vehicle_number = models.CharField(max_length=10)
    charges = models.IntegerField()
    tare_weight = models.IntegerField(null=True, blank=True)
    gross_weight = models.IntegerField(null=True, blank=True)
    net_weight = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.customer_name

pracproject/myproject/myapp/forms.py
from django import forms
from .models import Person, NewUser, CustomerEntry
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'


class UserSignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')


class CustomerEntryForm(forms.ModelForm):
    class Meta:
        model = CustomerEntry
        fields = "__all__"

pracproject/myproject/myapp/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, DeleteView, UpdateView
from django.contrib.auth.models import User
from .models import Person, NewUser, CustomerEntry
from .forms import PersonForm, UserSignupForm, CustomerEntryForm


# Create your views here.


# noinspection PyUnresolvedReferences
class HomePage(TemplateView):
    template_name = 'base.html'


# noinspection PyUnresolvedReferences
class PersonListView(ListView):
    model = Person
    template_name = 'about.html'

    def get_queryset(self):
        return Person.objects.all()


class PersonDetailView(LoginRequiredMixin, DetailView):
    # login_url = '/accounts/login/'
    model = Person
    template_name = 'detail.html'


class CreatePersonView(CreateView):
    template_name = 'add_person.html'
    model = Person
    form_class = PersonForm

    def form_valid(self, form):
        print(form.cleaned_data.get("name")+form.cleaned_data.get("age"))
        return super(CreatePersonView, self).form_valid(form)


class DeletePersonView(LoginRequiredMixin, DeleteView):
    # login_url = '/accounts/login/'
    model = Person
    success_url = reverse_lazy('person_list')


class UpdatePersonView(LoginRequiredMixin, UpdateView):
    model = Person
    form_class = PersonForm

    # def dispatch(self, request, *args, **kwargs):
    #     if self.request.user.is_staff:
    #         raise PermissionDenied
    #     return super().dispatch(request, *args, **kwargs)


class SignUpView(CreateView):
    template_name = 'signup.html'
    form_class = UserSignupForm
    model = NewUser
    success_url = reverse_lazy('user_login')




class CustomerEntryView(CreateView):
    template_name = 'create_customer.html'
    form_class = CustomerEntryForm
    model = CustomerEntry
    success_url = reverse_lazy('customer_list')


class CustomerListView(ListView):
    context_object_name = "customer_objects"
    model = CustomerEntry
    template_name = 'customer_list.html'

    def get_queryset(self):
        return CustomerEntry.objects.all()


class UpdateCustomerView(UpdateView):
    model = CustomerEntry
    form_class = CustomerEntryForm
    template_name = 'customer_update_form.html'
    success_url = reverse_lazy('customer_list')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)


class CustomerInformation(DetailView):

    model = CustomerEntry
    template_name = 'customer_info.html'


class Practice(TemplateView):
    template_name = 'practice.html'

pracproject/myproject/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{%load static %}


{% block content %}



    {% if user.is_superuser%}
        <div class="container">
            <div class="jumbotron text-center">
                {% if object_list %}
                    {% for data in object_list %}
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-4" ><a href="{% url 'person_detail' pk=data.pk%}"><h1>{{data.name}}</h1> </a></div>
                            <div class="col-sm-4" ><a href="{% url 'delete_person' pk=data.pk %}"><h1>
                                <span class="glyphicon glyphicon-remove" data-toggle="Delete" data-placement="top" title="delete"></span></h1></a><br>
                            </div>
                            <div class="col-sm-4" ><a href="{% url 'update_person' pk=data.pk %}"><h1>
                                <span class="glyphicon glyphicon-edit" data-toggle="Update" data-placement="top" title="update"></span></h1></a><br>
                            </div>
                        </div>
                    </div>

                {% endfor %}

                {% else %}
                    <h1>There is no longer details</h1>
                {%endif%}


            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron text-center">
                <h1>You are not SuperUser</h1>
            </div>
        </div>

    {% endif %}



    <script type="text/javascript" src="{% static 'myapp/js/about.js'%}"></script>
<!--    <button class="click" name="click" value="click">click</button>-->


{% endblock %}

pracproject/myproject/myapp/templates/myapp/add_person.html
{% extends 'myapp/base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron text-center">
            <form method="POST" class="post-form">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="save btn btn-default">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

pracproject/myproject/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">

    <title>BASE HTML</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="{%static 'css/base.css' %}">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<!--    <script type="text/javascript" src="{% static 'myapp/js/base.js'%}"></script>-->


</head>


<body style="background-image:url('{%static 'myapp/images/bg4.jpg'%}');" >

    <div class="base-navbar">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                  <a class="navbar-brand" href="#">MyApplication</a>
                </div>

                <ul class="nav navbar-nav">
                    <li class=""><a href="{% url 'home_page' %}">Home</a></li>
                    <li class=""><a href="{% url 'person_list' %}">About</a></li>
                    <li class=""><a href="{% url 'practice' %}">Practice</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Services<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Service-1</a></li>
                            <li><a href="#">Service-2 </a></li>
                            <li><a href="#">Service-3</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">

                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}" >Logout</a>
                        </li>

                        {% if user.is_superuser %}
                            <li>
                                <a  href="{% url 'new_customer_entry' %}" >Entry</a>
                            </li>
                            <li>
                                <a  href="{% url 'customer_list' %}" >Customers</a>
                            </li>
                            <li>
                                <a  href="{% url 'add_person' %}" >Add</a>
                            </li>
                            <li>
                                <a >Welcome: {{ user.username }}</a>
                            </li>

                        {%else%}

                            <li>
                                <a> Welcome User: {{ user.username }}</a>
                            </li>

                        {% endif %}

                    {% else %}

                        <li><a  href="{% url 'user_login' %}" ><span  style="margin:5px;" class=""></span>Login</a></li>
                        <li><a  href="{% url 'signup' %}" ><span  style="margin:5px;" class=""></span>SignUp</a></li>
                        <li><a  href="{% url 'login' %}" ><span  style="margin:5px;" class="glyphicon glyphicon-user"></span></a></li>

                    {% endif %}

                </ul>
            </div>
        </nav>
    </div>


    <div class="base-header">
        <div class="container">
            <div class="jumbotron text-center">
                <h1>Base</h1>
            </div>
        </div>
    </div>

    <div class="base-main">
            {% block content %}
                <div class="container new">
                    <div class="text-center">
                        <h1>Welcome Home Page</h1>
                    </div>
                </div>

            {% if user.is_authenticated%}
                <div class="container">
                    <div class="text-center">
        <!--                <img src="{%static 'myapp/images/welcome.jpg'%}" width="500px" height="500px">-->
                    </div>
                </div>
            {% endif %}
                <br>
                <div class="container ">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="width:100%;height:500px;margin:auto;">
                      <!-- Indicators -->
                      <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>

                      </ol>

                      <!-- Wrapper for slides -->
                      <div class="carousel-inner" role="listbox">
                        <div class="item active">
                          <img style="width:100%;height:500px;" src="{%static 'myapp/images/bg.jpg'%}" alt="Los Angeles">
                        </div>

                        <div class="item">
                          <img style="width:100%;height:500px;" src="{%static 'myapp/images/welcome.jpg'%}" alt="Chicago">
                        </div>

                      </div>

                      <!-- Left and right controls -->
                        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                            <span class="icon-prev" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                            <span class="icon-next" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>

                    </div>
                </div>
            {% endblock %}

    </div>


    <div class="base-footer">

        <footer class="page-footer font-small blue pt-4 footer" id="new">
            <div class="container-fluid text-center text-md-left">

                <div class="row">

                    <div class="col-md-6 ">
                        <h3 class="text-uppercase text-center">Footer Content</h3>
                        <p>Here you can use rows and columns to organize your footer content.</p>
                    </div>

                    <div class="col-md-3 ">
                        <h5 class="text-uppercase ">Links</h5>

                        <ul class="list-unstyled">
                          <li>
                            <a href="#!">Link 1</a>
                          </li>
                          <li>
                            <a href="#!">Link 2</a>
                          </li>
                          <li>
                            <a href="#!">Link 3</a>
                          </li>
                          <li>
                            <a href="#!">Link 4</a>
                          </li>
                        </ul>
                    </div>

                    <div class="col-md-3">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled">
                            <li>
                                <a href="#!">Link 1</a>
                            </li>
                            <li>
                                <a href="#!">Link 2</a>
                            </li>
                            <li>
                                <a href="#!">Link 3</a>
                            </li>
                            <li>
                                <a href="#!">Link 4</a>
                            </li>
                        </ul>
                    </div>

                </div>


                </div>

                    <div class="footer-copyright text-center py-3 copy-right">© 2020 Copyright:
                        <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
                    </div>

        </footer>
    </div>



</body>
</html>

pracproject/myproject/myapp/templates/myapp/create_customer.html
{% extends 'myapp/base.html' %}
{% load bootstrap3 %}
{%load static %}
{% block content %}
    <div class="container">
        <div class="jumbotron ">
            <form method="POST" class="post-form">
                {% csrf_token %}
<!--                {{ form.as_p}}-->
<!--                {{ form.as_table}}-->
                {% bootstrap_form form %}
                <button type="submit" class="save btn btn-default">Submit</button>
            </form>
        </div>
    </div>

    <script type="text/javascript" src="{% static 'myapp/js/create_customer.js'%}"></script>
{% endblock %}

pracproject/myproject/myapp/templates/myapp/customer_info.html
{% extends 'myapp/base.html' %}

{% block content %}

    <div class="container">
        <div class="jumbotron  text-center ">
            <div class="container container-fluid ">
                <div class="row">
                    <div class="col-sm-6 "> <b>RST Number</b> </div>
                    <div class="col-sm-6 " >{{object.rst_number}}</div>

                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6 " ><b>Customer Name</b> </div>
                    <div class="col-sm-6 " >{{object.customer_name}}</div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6" ><b>Vehicle Number</b> </div>
                    <div class="col-sm-6" >{{object.vehicle_number}}</div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6" ><b>Charges</b> </div>
                    <div class="col-sm-6" >{{object.charges}}</div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6" ><b>Tare Weight</b> </div>
                    <div class="col-sm-6" >{{object.tare_weight}}</div>
                </div>
                <hr>
                <div class="row">
                     <div class="col-sm-6" ><b>Gross Weight</b> </div>
                    <div class="col-sm-6" >{{object.gross_weight}}</div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6" ><b>Net Weight</b> </div>
                    <div class="col-sm-6" >{{object.net_weight}}</div>
                </div>
                <hr>
            </div>
        </div>
    </div>


{% endblock %}

pracproject/myproject/myapp/templates/myapp/customer_list.html
{% extends 'myapp/base.html' %}
{%load static %}


{% block content %}

<!--    <div class="container">-->
<!--        <div class="jumbotron text-center">-->

<!--            {% if customer_objects %}-->

<!--                {% for data in customer_objects %}-->

<!--                    <div class="container-fluid">-->
<!--                        <div class="row">-->
<!--                            <div class="col-sm-3" ><a href="{% url 'person_detail' pk=data.pk%}">{{data.rst_number}}</a></div>-->
<!--                            <div class="col-sm-3" ><a href="{% url 'person_detail' pk=data.pk%}">{{data.customer_name}}</a></div>-->
<!--                            <div class="col-sm-3" ><a href="{% url 'person_detail' pk=data.pk%}">{{data.vehicle_number}}</a></div>-->
<!--                            <div class="col-sm-3" ><a href="{% url 'update_customer' pk=data.pk %}">-->
<!--                                <span class="glyphicon glyphicon-edit" data-toggle="Update" data-placement="top" title="update"></span></a><br>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->

<!--            {% endfor %}-->

<!--            {% else %}-->
<!--                <h1>There is no customer details</h1>-->
<!--            {%endif%}-->


<!--        </div>-->
<!--    </div>-->


    <div class="container">
        <div class="jumbotron">
            {% if customer_objects %}
                <h2>Filterable Table</h2>
                <p>Type something in the input field to search the table for RST Number:</p>
    <!--            Search...<input class="form-control" id="input" type="text" placeholder="Search.."><br>-->
                <input class="form-control" id="myInput" type="text" placeholder="Search.."><br>
                <table class="table table-bordered table-striped text-center">
                    <thead>
                      <tr >
                        <th class="text-center">Rst Number</th>
    <!--                    <th class="text-center">Customer Name</th>-->
    <!--                    <th class="text-center">Vehicle Number</th>-->
                          <th class="text-center">Update</th>
                          <th class="text-center">Customer Info</th>
                      </tr>
                    </thead>
                    {% for data in customer_objects %}
                        <tbody id="myTable" >
                            <tr>
                                <td data-toggle="Update" data-placement="top" title={{data.customer_name}} >
                                    {{data.rst_number}}
                                </td>
    <!--                            <td>{{data.customer_name}}</td>-->
    <!--                            <td>{{data.vehicle_number}}</td>-->
                                <td>
                                    <a href="{% url 'update_customer' pk=data.pk %}">
                                        <span class="glyphicon glyphicon-edit" data-toggle="Update" data-placement="top" title="update"></span>
                                    </a><br>
                                </td>
                                <td>
                                    <a href="{% url 'customer_info' pk=data.pk %}">
                                        <span class="glyphicon glyphicon-info-sign" data-toggle="Information" data-placement="top" title="Information"></span>
                                    </a><br>
                                </td>
                            </tr>

                        </tbody>
                    {% endfor %}

              </table>
                    <p>Note that we start the search in tbody, to prevent filtering the table headers.</p>
            {% else %}
                    <h1>There is no Longer Customers</h1>
            {%endif%}
        </div>
    </div>

    <script type="text/javascript" src="{% static 'myapp/js/customer_list.js'%}"></script>


{% endblock %}

pracproject/myproject/myapp/templates/myapp/customer_update_form.html
{% extends 'myapp/base.html' %}
{%load static %}

{% block content %}
    <div class="container">
        <div class="jumbotron text-center">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}

                <p>Are you sure you want to update customer "{{ object }}"?</p>
                <input class='btn btn-danger' type="submit" value="Confirm" />
                <a href="{%url 'customer_list'%}"><button class="btn btn-danger" type="button">Cancel</button></a>
            </form>
        </div>
    </div>



    <script type="text/javascript" src="{% static 'myapp/js/customer_update.js'%}"></script>


{% endblock %}

pracproject/myproject/myapp/templates/myapp/customerentry_form.html
{% extends 'myapp/base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron text-center">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}

                <p>Are you sure you want to update customer "{{ object }}"?</p>
                <input class='btn btn-danger' type="submit" value="Confirm" />
                <a href="{%url 'customer_list'%}"><button class="btn btn-danger" type="button">Cancel</button></a>
            </form>
        </div>
    </div>


    <script
                src="https://code.jquery.com/jquery-3.5.1.min.js"
                integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
                crossorigin="anonymous">
    </script>

    <script>
    $(document).ready(function(){
      $("#id_gross_weight").on("keyup", function() {
        var net_weight = $("#id_gross_weight").val() - $("#id_tare_weight").val()
        $("#id_net_weight").val(net_weight);
      });
    });
    </script>

{% endblock %}

pracproject/myproject/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron text-center">
            <div class="container container-fluid">
                <div class="row">
                    <div class="col-sm-6"> <b>NAME</b> </div>
                    <div class="col-sm-6" ><b>AGE</b> </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6" >{{object.name}}</div>
                    <div class="col-sm-6" >{{object.age}}</div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

pracproject/myproject/myapp/templates/myapp/person_confirm_delete.html
{% extends 'myapp/base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron text-center">
            <form action="" method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <input class='btn btn-danger' type="submit" value="Confirm" />
                <a href="{%url 'person_list'%}"><button class="btn btn-danger" type="button">Cancel</button></a>
            </form>
        </div>
    </div>

{% endblock %}

pracproject/myproject/myapp/templates/myapp/person_form.html
{% extends 'myapp/base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron text-center">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <p>Are you sure you want to update "{{ object }}"?</p>
                <input class='btn btn-danger' type="submit" value="Confirm" />
                <a href="{%url 'person_list'%}"><button class="btn btn-danger" type="button">Cancel</button></a>
            </form>
        </div>
    </div>

{% endblock %}

pracproject/myproject/myapp/templates/myapp/practice.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">

    <title>BASE HTML</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="{%static 'css/practice.css' %}">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="{% static 'js/practice.js'%}"></script>


</head>


<body style="background-image:url('{%static 'myapp/images/bg4.jpg'%}');" >

    <div class="base-navbar">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                  <a class="navbar-brand" href="#">MyApplication</a>
                </div>

                <ul class="nav navbar-nav">
                    <li class=""><a href="{% url 'home_page' %}">Home</a></li>

                </ul>

                <ul class="nav navbar-nav navbar-right">

                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}" >Logout</a>
                        </li>

                        {% if user.is_superuser %}

                            <li>
                                <a >Welcome: {{ user.username }}</a>
                            </li>

                        {%else%}

                            <li>
                                <a> Welcome User: {{ user.username }}</a>
                            </li>

                        {% endif %}

                    {% else %}

                        <li><a  href="{% url 'user_login' %}" ><span  style="margin:5px;" class=""></span>Login</a></li>
                        <li><a  href="{% url 'signup' %}" ><span  style="margin:5px;" class=""></span>SignUp</a></li>
                        <li><a  href="{% url 'login' %}" ><span  style="margin:5px;" class="glyphicon glyphicon-user"></span></a></li>

                    {% endif %}

                </ul>
            </div>
        </nav>
    </div>

    <div class="base-sidebar">
        <div class="list">
            <div class="item">Home</div>
            <div class="item">Service</div>
            <div class="item">About</div>
        </div>

<!--        <div class="sidebar-btn">-->
<!--            <span></span>-->
<!--            <span></span>-->
<!--            <span></span>-->
<!--        </div>-->

            <span class=" sidebar-btn glyphicon glyphicon-align-justify"></span>
    </div>



    <div class="base-header">
        <div class="container">
            <div class="jumbotron text-center">
                <h1>Base</h1>
            </div>
        </div>
    </div>

    <div class="base-main">
        <div class="container">
            <div class="jumbotron">
                main
            </div>
        </div>
    </div>



    <div class="base-footer">
        <div class="row">
            <div class="col-md-4 ">
                <h3 class="text-uppercase text-center">Footer Content</h3>
                <p>Here you can use rows and columns to organize your footer content.</p>
            </div>
            <div class="col-md-4 ">
                <h5 class="text-uppercase ">Links</h5>
                <ul class="list-unstyled">
                    <li>link 1</li>
                    <li>link 2</li>
                    <li>link 3</li>
                    <li>link 4</li>
                </ul>
            </div>
            <div class="col-md-4 ">
                <h5 class="text-uppercase ">Links</h5>
                <ul class="list-unstyled">
                    <li>link 1</li>
                    <li>link 2</li>
                    <li>link 3</li>
                    <li>link 4</li>
                </ul>
            </div>
        </div>

        <div class=" footer-bottom ">© 2020 Copyright:
            <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
        </div>
    </div>



</body>
</html>

pracproject/myproject/myapp/templates/myapp/signup.html
{% extends 'myapp/base.html' %}
{% load bootstrap3 %}
{% block content %}
    <div class="container">
        <div class="jumbotron ">
            <form method="POST" class="post-form">
                {% csrf_token %}
<!--                {{ form.as_p}}-->
                {% bootstrap_form form %}
                <button type="submit" class="save btn btn-default">Signup</button>
            </form>
        </div>
    </div>

{% endblock %}